apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: baggage-filter
  namespace: cluster
spec:
  selector:
    matchLabels:
      app: gateway
  url: docker-registry.anyflow.net/baggage-filter:0.1.2
  imagePullPolicy: Always
  phase: STATS
  failStrategy: FAIL_OPEN
  #  priority: 9
  pluginConfig:
    headers:
      - "header-to-add-in-baggage"
